config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  scope :api do
    scope :v1 do
      resources :jornals

    end
  end

end

app/models/jornal.rb
class Jornal
  include Elasticsearch::API

  CONNECTION = ::Faraday::Connection.new url: 'http://localhost:9200'

  def perform_request method, path, params, body
    puts "--> #{method.upcase} #{path} #{params} #{body}"

    CONNECTION.run_request method.downcase.to_sym,
                           path,
                           (body ? MultiJson.dump(body) : nil),
                           {'Content-Type' => 'application/json'}
  end

  def self.mapear

    uri = URI(Rails.configuration.elasticsearch_configuracoes.host + Rails.configuration.elasticsearch_configuracoes.nome_indice)
    req_put = Net::HTTP::Put.new(uri)
    req_put.content_type = 'application/json'
    req_put.body = $elasticsearch_analyzer.to_json

    res = Net::HTTP.start(uri.host, uri.port) do |http|
      http.request(req_put)
    end

  end

  def self.indexar ano, caminho_arquivo, tipo_extracao

    conteudo = String.new
    case tipo_extracao
      when "tika"
        conteudo = Jornal.extrair_tika caminho_arquivo
      when "somente tesseract"
        conteudo = Jornal.extrair_conteudo_arquivo_somente_tesseract caminho_arquivo
      when "convert tesseract"
        conteudo = Jornal.extrair_conteudo_arquivo_convert_tesseract caminho_arquivo
      when "convert cleaner tesseract"
        conteudo = Jornal.extrair_conteudo_arquivo_convert_cleaner_tesseract caminho_arquivo
    end

    #conteudo = ExtracaoConteudoArquivo.extrair caminho_arquivo
    client = Jornal.new

    diretorio_relativo = "thumbs/"
    nome_thumbnail = File.basename(caminho_arquivo, File.extname(caminho_arquivo)) << "_thumb.png"
    caminho_relativo = diretorio_relativo << nome_thumbnail

    novo_jornal = {
        ano: ano,
        tipo_extracao: tipo_extracao,
        caminho_arquivo: caminho_arquivo,
        jornal_thumb: caminho_relativo,
        conteudo: conteudo
    }

    caminho_absoluto = Rails.root.join('app', 'assets', 'images', 'thumbs') + nome_thumbnail

    stdout_thumbnail = `convert #{caminho_arquivo} -thumbnail 120x90 #{caminho_absoluto}`

    p client.index index: 'museu_digital', type: 'jornal', body: novo_jornal

  end

  def self.pesquisar termo, options={}
    query = Jornal.definir_pesquisa termo, options
    client = Jornal.new
    p client.search index: 'museu_digital', body: query
  end

  def self.pesquisar_jornal id

    url = "http://localhost:9200/museu_digital/jornal/#{id}"

    search_definition = {
        _source: ['caminho_arquivo'],
        query: {
            term: { _id: id}
        }
    }

    client = Jornal.new
    p client.search index: 'museu_digital', body: search_definition
  end

  private

  def self.definir_pesquisa termo, options={}

    search_definition = {
        _source: ['ano', 'jornal_thumb'],
        aggs: {},
        highlight: {},
        query: {}
    }

    search_definition[:aggs] = definir_clausula_aggregation
    search_definition[:highlight] = definir_clausula_highlight
    search_definition[:query] = definir_clausula_query termo
    if !options.empty?
      incluir_agregacao search_definition, options
    end
    return search_definition
  end

  def self.definir_clausula_aggregation
    aggregation = {
      ano: { terms: {field: 'ano'}}
    }
  end

  def self.definir_clausula_highlight
    highlight = {
        pre_tags: ["<b>"],
        post_tags: ["</b>"],
        fragment_size: 150,
        number_of_fragments: 3,
        fields: {
            ano: { require_field_match: false },
            conteudo: { require_field_match: false }
        }
    }
  end

  def self.definir_clausula_query termo
    query_clause = {
        bool: {
            must: [
              {
                  query_string: {
                      fields: ["conteudo"],
                      query: termo,
                      fuzziness: 2
                  }
              }
            ]
        }
    }
  end

  def self.incluir_agregacao search_definition, options

    if options[:anosList]
      anos = options[:anosList].split(",").map { |s| s.to_i }
        termo_ano = {}
        termo_ano[:terms] = {}
        termo_ano[:terms][:ano] = {}
        termo_ano[:terms][:ano] = anos
        search_definition[:query][:bool][:must] << termo_ano


    end
  end

  def self.extrair_conteudo_arquivo_somente_tesseract caminho_do_arquivo
    stdout = `tesseract #{caminho_do_arquivo} stdout -l por+eng`
    conteudo_formatado = stdout.gsub(/[\n\t\r]/m, ' ').gsub(/\s+/m, ' ').strip
    return conteudo_formatado
  end

  def self.extrair_conteudo_arquivo_convert_tesseract caminho_do_arquivo

    arquivo = caminho_do_arquivo.match(/([a-z0-9]+)\.([a-z0-9]+)$/i)
    caminho_do_arquivo_tiff = "tmp/#{arquivo[1]}.tiff"
    `convert #{caminho_do_arquivo} -type Grayscale #{caminho_do_arquivo_tiff}`
    stdout = `tesseract #{caminho_do_arquivo_tiff} stdout -l por+eng`
    conteudo_formatado = stdout.gsub(/[\n\t\r]/m, ' ').gsub(/\s+/m, ' ').strip
    return conteudo_formatado
  end

  def self.extrair_conteudo_arquivo_convert_cleaner_tesseract caminho_do_arquivo

    arquivo = caminho_do_arquivo.match(/([a-z0-9]+)\.([a-z0-9]+)$/i)
    caminho_do_arquivo_tiff = "tmp/#{arquivo[1]}.tiff"
    `convert #{caminho_do_arquivo} -type Grayscale #{caminho_do_arquivo_tiff}`

    cleaner = File.join(Rails.root, 'lib', 'tika', 'textcleaner')
    caminho_do_arquivo_tiff_clean = caminho_do_arquivo_tiff.gsub('.tiff', '.clean.tiff')
    `#{cleaner} -u -T -p 10 #{caminho_do_arquivo_tiff} #{caminho_do_arquivo_tiff_clean}`

    stdout = `tesseract #{caminho_do_arquivo_tiff_clean} stdout -l por+eng`
    conteudo_formatado = stdout.gsub(/[\n\t\r]/m, ' ').gsub(/\s+/m, ' ').strip
    return conteudo_formatado
  end

  def self.extrair_tika caminho_arquivo
    stdout = `java -jar lib/tika/tika-app-1.12.jar #{caminho_arquivo}`
    conteudo_formatado = stdout.gsub(/[\n\t\r]/m, ' ').gsub(/\s+/m, ' ').strip
    return conteudo_formatado
  end

end

app/controllers/jornals_controller.rb
class JornalsController < ApplicationController

  def create
    Jornal.indexar ano, caminho_arquivo, tipo_extracao
  end

  def index
    @termo=params[:termo]
    parametros={}
    @ano_selecionado=false
    if params[:anosList]
      parametros[:anosList] = params[:anosList]
      @ano_selecionado=true
    end
    resultado = JSON.parse(Jornal.pesquisar @termo, parametros)
    @jornais = resultado['hits']
    @agregacoes = resultado['aggregations']

  end

  def show
    jornal = JSON.parse(Jornal.pesquisar_jornal params[:id])
    caminho_arquivo = jornal['hits']['hits'][0]['_source']['caminho_arquivo']
    File.open(caminho_arquivo) do |f|
      send_data f.read, :type => "image/jpeg", :disposition => "inline"
    end
  end

  def self.testar_indexacao ano
    #Jornal.indexar ano, caminho_arquivo, "tika"
    Dir.foreach('arquivos/jornais') do |nome_arquivo|
      next if nome_arquivo == '.' or nome_arquivo == '..' or nome_arquivo == '.DS_Store'
      # do work on real items
      caminho_arquivo = '/Users/guilhermemaranhao/Projetos/ruby/museu_digital/app/museu_digital/arquivos/jornais/' + nome_arquivo
      Jornal.indexar ano, caminho_arquivo, "somente tesseract"
      #Jornal.indexar ano, caminho_arquivo, "convert tesseract"
      #Jornal.indexar ano, caminho_arquivo, "convert cleaner tesseract"
    end

    Dir.foreach('arquivos/revistas') do |nome_arquivo|
      next if nome_arquivo == '.' or nome_arquivo == '..'
      # do work on real items
      caminho_arquivo = '/Users/guilhermemaranhao/Projetos/ruby/museu_digital/app/museu_digital/arquivos/revistas/' + nome_arquivo
      Jornal.indexar ano, caminho_arquivo, "somente tesseract"
      #Jornal.indexar ano, caminho_arquivo, "convert tesseract"
      #Jornal.indexar ano, caminho_arquivo, "convert cleaner tesseract"
    end

  end

end

app/views/jornals/index.html.erb
<<% content_for :container do %>
    <div>
      <div class="row">
        <a class="btn btn-primary btn-atualizar" type="button" onclick="atualizarPesquisa()">Atualizar</a>
      </div>
      <% if @jornais && @jornais['hits'].length > 0 %>
      <div class="col-md-3">
        <div class="row">Ano </div>

        <% (0..@agregacoes['ano']['buckets'].length-1).each do |i|%>
            <div class="row">
              <a class="link-ano" id="link-ano-<%=@agregacoes['ano']['buckets'][i]['key']%>" onclick="alterarFiltros(<%=@agregacoes['ano']['buckets'][i]['key']%>)">
                <%= @agregacoes['ano']['buckets'][i]['key'] %></a>
              (<%= @agregacoes['ano']['buckets'][i]['doc_count'] %>)
            </div>
        <% end %>
        <% if @ano_selecionado %>
            <a href="jornals?termo=<%=@termo%>">Refazer</a>
        <% end %>
      </div>
      <div class="col-md-9">
        <% (0..@jornais['hits'].length-1).each do |i| %>
            <div class="row list-group-item jornal-ano-<%=@jornais['hits'][i]['_source']['ano']%>">
              <div class="col-md-2">
                <div class="row">
                <span><a href="jornals/<%=@jornais['hits'][i]['_id']%>"><%= image_tag(@jornais['hits'][i]['_source']['jornal_thumb'], :class => "img-thumbnail")%></a></span>
                  </div>
                <div class="row">
                <span>Ano: <%= @jornais['hits'][i]['_source']['ano']%></span>
                  </div>
              </div>

              <div class="col-md-10">

                <% (0..@jornais['hits'][i]['highlight']['conteudo'].length-1).each do |j| %>
                    <%= @jornais['hits'][i]['highlight']['conteudo'][j] %>
                <% end %>
              </div>
            </div>
        <% end %>
      </div>
      </p>
          <% else %>
      <h4>Não foram encontrados resultados com o termo "<b><%= @termo %></b>"</h4>
          <%end%>
    </div>

    <script type="application/javascript">
      var anosList = new Array();
      var precisaAtualizar = false;

      function alterarFiltros(ano){
          if(anosList.length == 0){
              $('.link-ano').css('text-decoration','line-through');
              $('.link-ano').css('opacity','0.4');
              $('.list-group-item').css('display','none');
              anosList.push(ano);
              $('#link-ano-'+ano).css('text-decoration','none');
              $('#link-ano-'+ano).css('opacity','1.0');
              $('.jornal-ano-'+ano).css('display','block');
          }
          else{
              itemIndex = $.inArray( ano, anosList);
              if(itemIndex == -1) {
                  anosList.push(ano);
                  $('#link-ano-'+ano).css('text-decoration','none');
                  $('#link-ano-'+ano).css('opacity','1.0');
                  $('.jornal-ano-'+ano).css('display','block');
              }else{
                  anosList.splice(itemIndex,1);
                  $('#link-ano-'+ano).css('text-decoration','line-through');
                  $('#link-ano-'+ano).css('opacity','0.4');
                  $('.jornal-ano-'+ano).css('display','none');
              }
          }


          precisaAtualizar = true;
      };
            function  atualizarPesquisa(){
                var path = '<%= jornals_path %>';
                Turbolinks.visit( path+'?termo=<%=@termo%>&anosList=' + anosList);
            }


    </script>
<% end %>